[package]
name = "ggez"
description = "Rust library to create a Good Game Easily"
version = "0.1.0"
repository = "https://github.com/ggez-dev/ggez"
documentation = "https://docs.rs/ggez"
keywords = ["ggez", "graphics", "2D", "game", "engine"]
authors = [
   "Rafael Epplee <raffomania@gmail.com>", 
   "Sven-Hendrik Haase <svenstaro@gmail.com>",
   "Simon Heath <icefoxen@gmail.com"
]
license = "MIT"
readme = "README.md"

[lib]
name = "ggez"
path = "src/lib.rs"

[dependencies]
sdl2 = "0.23"
sdl2-sys = "0.23"
sdl2_image = "0.23"
sdl2_mixer = "0.23"
sdl2_ttf = "0.23"
rand = "0.3"
lazy_static = "0.2"
zip = "0.1"

rustc-serialize = "0.3"
toml = "0.2"

